# Generated by Django 4.1.1 on 2022-09-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0003_alter_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
