# Generated by Django 4.1 on 2022-09-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0007_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.IntegerField(choices=[(0, 'No order'), (1, 'Order Sent'), (2, 'Order Complete')], default=0),
        ),
    ]
