# Generated by Django 4.1 on 2022-09-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0011_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='list_order',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_add',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
