# Generated by Django 4.1 on 2022-09-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0012_order_list_order_alter_order_created_add_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
