# Generated by Django 4.1 on 2022-09-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0013_delete_userorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
