# Generated by Django 4.1 on 2022-09-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0014_alter_order_total_price_alter_order_tracking_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='list_order_json',
            field=models.JSONField(null=True),
        ),
    ]
