# Generated by Django 4.1 on 2022-09-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0016_order_address_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='list_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Order Received'), (1, 'On-Delivery'), (2, 'Delivered')], default=0),
        ),
    ]
