# Generated by Django 4.1 on 2022-09-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0017_remove_order_list_order_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Payment Received', 'Payment Received'), ('On-Delivery', 'On-Delivery'), ('Delivered', 'Delivered')], default='Payment Received', max_length=30),
        ),
    ]
