# Generated by Django 4.1 on 2022-09-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0021_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
    ]
