# Generated by Django 4.1.1 on 2022-09-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0022_remove_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
