# Generated by Django 4.1 on 2022-09-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0023_alter_order_created_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_times',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Payment Received', 'Payment Received'), ('On Progress', 'On Progress'), ('Complete', 'Complete')], default='Payment Received', max_length=30),
        ),
    ]
