# Generated by Django 4.1 on 2022-09-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0024_order_completed_times_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New-Order', 'New-Order'), ('Process', 'Process'), ('Complete', 'Complete')], default='New-Order', max_length=30),
        ),
    ]
