# Generated by Django 4.1.1 on 2022-09-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopikuy', '0025_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/images/user.png', null=True, upload_to=''),
        ),
    ]
